openapi: 3.0.0
info:
  title: FeedForward API
  version: 1.0.0
  description: API documentation for the FeedForward backend.
servers:
  - url: http://localhost:5000/api/v1
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - username
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                username:
                  type: string
                password:
                  type: string
                  format: password
                avatar:
                  type: string
                  format: uri
                bio:
                  type: string
                interests:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Logged in successfully
        '400':
          description: Invalid credentials
  # Add more paths for other endpoints
